export const configLink = {
  home: '/',
  search: '/search/',
  searchMobile: '/search-mobile',
  movies: '/movies',
  series: '/series',
  cartoons: '/cartoons',
  anime: '/anime',
  tvShows: '/tv-shows',
  top250Films: '/top250Films',
  film: '/film/',
  fullCast: '/film/full-cast/',
  person: '/person/',
  company: '/company/',
  director: '/director/',
  country: '/country/',
  genres: '/genres/',
};
