export const configLink = {
  home: '/',
  search: '/search/',
  searchMobile: '/search-mobile',
  movies: '/movies',
  series: '/series',
  cartoons: '/cartoons',
  anime: '/anime',
  tvShows: '/tv-shows',
  top250Films: '/top250Films',
  top250TVs: '/top250TVs',
  inTheaters: '/in-theaters',
  comingSoon: '/coming-soon',
  boxOffice: '/box-office',
  boxOfficeAllTime: '/box-office-all-time',
  film: '/film/',
  fullCast: '/film/full-cast/',
  person: '/person/',
  company: '/company/',
  director: '/director/',
  country: '/country/',
  genres: '/genres/',
};
