import { IStarShort } from './IStarShort';
import { IActorShort } from './IActorShort';
import { IFullCastData } from './IFullCastData';
import { IKeyValueItem } from './IKeyValueItem';
import { ICompanyShort } from './ICompanyShort';
import { IRatingData } from './IRatingData';
import { IWikipediaData } from './IWikipediaData';
import { IPosterData } from './IPosterData';
import { IImageData } from './IImageData';
import { ITrailerData } from './ITrailerData';
import { IBoxOfficeShort } from './IBoxOfficeShort';
import { ITvSeriesInfo } from './ITvSeriesInfo';
import { ITvEpisodeInfo } from './ITvEpisodeInfo';
import { ISimilarShort } from './ISimilarShort';

export interface ITitleData {
  id: string;
  title: string;
  originalTitle: string;
  fullTitle: string;
  type: string;
  year: string;
  image: string;
  releaseDate: string;
  runtimeMins: string;
  runtimeStr: string;
  plot: string;
  plotLocal: string;
  plotLocalIsRtl: boolean;
  awards: string;
  directors: string;
  directorList: IStarShort[];
  writers: string;
  writerList: IStarShort[];
  stars: string;
  starList: IStarShort[];
  actorList: IActorShort[];
  fullCast: IFullCastData;
  genres: string;
  genreList: IKeyValueItem[];
  companies: string;
  companyList: ICompanyShort[];
  countries: string;
  countryList: IKeyValueItem[];
  languages: string;
  languageList: IKeyValueItem[];
  contentRating: string;
  imDbRating: string;
  imDbRatingVotes: string;
  metacriticRating: string;
  ratings: IRatingData;
  wikipedia: IWikipediaData;
  posters: IPosterData;
  images: IImageData;
  trailer: ITrailerData;
  boxOffice: IBoxOfficeShort;
  tagline: string;
  keywords: string;
  keywordList: string[];
  similars: ISimilarShort[];
  tvSeriesInfo: ITvSeriesInfo;
  tvEpisodeInfo: ITvEpisodeInfo;
  errorMessage: string;
}
